language: php

sudo: false

matrix:
  include:
    - php: 5.4
    - php: 5.5
    - php: 5.6
    - php: 7
    - php: nightly
    - php: hhvm
  allow_failures:
    - php: nightly
    - php: hhvm

before_script:
  - composer self-update
  - composer install --prefer-source  --no-interaction --no-scripts

script:
  - vendor/bin/phpunit --verbose --coverage-clover=coverage.clover

after_success:
  - if [[ "$TRAVIS_PHP_VERSION" != "hhvm" ]] && [[ "$TRAVIS_PHP_VERSION" != "nightly" ]]; then wget https://scrutinizer-ci.com/ocular.phar; fi
  - if [[ "$TRAVIS_PHP_VERSION" != "hhvm" ]] && [[ "$TRAVIS_PHP_VERSION" != "nightly" ]]; then php ocular.phar code-coverage:upload --format=php-clover coverage.clover; fi
